### ISSUE TITLE
panick at accessing a feature with try_component if the entity has the requested feature

### ISSUE THREAD

**Issue by florianjacob** [HeroesGrave/ecs-rs#12]
I was playing around with the tutorial, when I noticed this:
```rust
#[macro_use]
extern crate ecs;

use ecs::WorldBuilder;
use ecs::Components;
use ecs::Entity;

feature! {
    CanFly;
}

fn main() {
    let mut builder = WorldBuilder::new();
    builder.register_component::<CanFly>();

    let mut world = builder.build();

    let entity = world.build_entity(
        |&: c: &mut Components, e: Entity| {
            c.add(&e, CanFly);
        }
    );

    match world.try_component::<CanFly>(&entity) {
        Some(_) => println!("can fly"),
        None => println!("can't fly"),
    }
}
```

results in this:
```
-> % cargo run --verbose
       Fresh ecs v0.16.4
       Fresh ecstest v0.0.1 (file:///home/florian/Programming/rust/ecstest)
     Running `../target/ecstest`
thread '<main>' panicked at 'Index Out of Bounds', /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/ecs-0.16.4/src/buffer.rs:60
An unknown error occurred
```
This doesn't seem like intended behaviour, or is my code wrong?

If the entity doesn't have the CanFly feature, everything works as expected and it prints „can't fly“.

**Comment by HeroesGrave** [comment]
I think I must've messed up an if-statement somewhere which causes zero-sized components to panic with OOB.

**Comment by HeroesGrave** [comment]
Yep, it was. When converting the `u8` slice to the `T` slice I was specifying the length of the `u8` slice instead of the length of the `T` slice. So for zero-sized types it would be trying to return the first element of a slice with length 0.

**Comment by HeroesGrave** [comment]
As a side note, it is currently more efficient to use `has_component()` with zero-sized components because it only has to check a `Bitv` instead of checking the Bitv and then returning the (somewhat useless) component.

**Comment by HeroesGrave** [comment]
Uploaded fixed version to crates.io as `0.16.5`

**Comment by florianjacob** [comment]
Thanks for the efficiency hint on top. :smile:
