### ISSUE TITLE
[Tutorial] PrintMessage systems! macro error

### ISSUE THREAD

**Issue by ntimeu** [HeroesGrave/ecs-rs#31]
Hi,

I am following your tutorial to understand your implementation of an ECS, and when I want to define the PrintMessage system, I got a macro error : 

`   Compiling test v0.1.0 (file:///home/fouassierr/gites/test)
src/main.rs:34:9: 34:18 error: no rules expected the token `**print_msg**`
src/main.rs:34         print_msg: PrintMessage = PrintMessage("Hello World".to_string())
                       ^~~~~~~~~
Could not compile `test`.

To learn more, run the command again with --verbose.`

I am running stable rust (1.8.0) with latest cargo.

```rust
#[macro_use]
extern crate ecs;

use ecs::{World,BuildData,System,Process,DataHelper};

pub struct PrintMessage(pub String);

#[derive(Copy, Clone, Debug, PartialEq)]
pub struct Position {
    pub x: f64,
    pub y: f64,
}

components! {
    struct MyComponents {
        #[hot] position: Position,
        #[cold] respawn: Position,
    }
}

impl System for PrintMessage {
    type Components = MyComponents;
    type Services   = ();
}

impl Process for PrintMessage {
    fn process(&mut self, _: &mut DataHelper<MyComponents, ()>) {
        println!("{}", &self.0);
    }
}

systems! {
    struct MySystems<MyComponents, ()> {
        print_msg: PrintMessage = PrintMessage("Hello World".to_string())
    }
}

fn main() {
    let mut world = World::<MySystems>::new();
    let entity = world.create_entity(
        |entity: BuildData<MyComponents>, data: &mut MyComponents| {
            data.position.add(&entity, Position{x: 0.0, y: 0.0});
            data.respawn.add(&entity, Position{x: 0.0, y: 0.0});
        }
    );

    loop {
        world.update();
    }
}
```
Is this caused by my version of rust or am I doing wrong things ?

**Comment by HeroesGrave** [comment]
Argh. This is my fault. I've been quite busy lately and never got around to updating the tutorial.

Change it to the following and it should work:

```rust
systems! {
    struct MySystems<MyComponents, ()> {
        active: {
            print_msg: PrintMessage = PrintMessage("Hello World".to_string())
        }
        passive: {}
    }
}
```

**Comment by ntimeu** [comment]
Hi HeroesGrave, thanks for the fast reply !

I changed the code according to your message, but it seems to error on the closing '}' of the 'active' block :
`
   Compiling tst v0.1.0 (file:///home/fouassierr/gites/tst)
src/main.rs:36:9: 36:10 error: no rules expected the token `}`
src/main.rs:36         }
                       ^
Could not compile `tst`.

To learn more, run the command again with --verbose.
`
I attach the following Gist with the modified code : https://gist.github.com/ntimeu/19364d510ae1f7a0384ea4a0c37426f4

I looked at the macro definition, but I did not find anything causing the error (as I am not very fluent with macros right now ^^).

**Comment by HeroesGrave** [comment]
Probably a missing comma.

try adding a comma to this line:
```rust
print_msg: PrintMessage = PrintMessage("Hello World".to_string())
```

**Comment by ntimeu** [comment]
Thanks, it works now ! I should have worked more on the macro syntax :(

**Comment by HeroesGrave** [comment]
The current situation isn't very nice to use. I'm planning a rewrite of the library but at the moment I'm busy trying to release a game.
