### ISSUE TITLE
Write a Tutorial

### ISSUE THREAD

**Issue by HeroesGrave** [HeroesGrave/ecs-rs#6]

**Comment by bluss** [comment]
Naive question coming:

To handle rendering completely outside the ecs, everything seems to be there except for one thing.. An entity iterator from the World object! Wouldn't that be logical to add? (Even though it allows less "pure" usage of the ECS).

**Comment by jamiltron** [comment]
What is the best way to pass in the delta time between frames to systems that require it? By instantiating their process with a Rc to a shared timer object, or some other way?

**Comment by HeroesGrave** [comment]
> Naive question coming:
> 
> To handle rendering completely outside the ecs, everything seems to be there except for one thing.. An entity iterator from the World object! Wouldn't that be logical to add? (Even though it allows less "pure" usage of the ECS).
Hmm. I'm certainly open to suggestions that make the framework more usable as long as they don't have a negative impact on the intended use. I think this will be possible to do.

> What is the best way to pass in the delta time between frames to systems that require it? By instantiating their process with a Rc to a shared timer object, or some other way?
Well, my first recommendation would be to use a fixed timestep. If you're not up for that, there are several ways around it, eg: `Rc<Cell<f32>>`, a scoped_thread_local.

**Comment by HeroesGrave** [comment]
@bluss: I just pushed version `0.16.3` to crates.io. World now has a `with_entities(F) where F: FnMut(&Entity)`. It loops through all active entities and calls the function with them. For direct use with iterators I will need to do a big cleanup of `World`, which I don't have the time for right now and may not even be possible.

**Comment by bluss** [comment]
Nice! I recognize the problem, with RefCells we can't return any borrowed values.

**Comment by HeroesGrave** [comment]
Closing because the basic tutorial is more or less done.
